### ISSUE TITLE
Pixel density 

### ISSUE THREAD

**Issue by JanVais** [zezioen/XamarinPainter#3]
This image should say A1

![sig](https://user-images.githubusercontent.com/20706450/31075289-170f0a56-a775-11e7-8b6e-2d655e144c2c.jpg)

**Comment by zezioen** [comment]
The issue is that the width and height which are provided don't take into account the density of the device, this doesn't seem to be an issue when providing the width and height of a background image. The solution will be to add a boolean paramater to indicate wether or not to use the device pixel density.

**Comment by zezioen** [comment]
Has since been fixed, you can now take in the device density when exporting an image
